apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-eco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-eco
  template:
    metadata:
      labels:
        app: worker-eco
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Never
        env:
        - name: MODE
          value: "ECO"
        - name: REDIS_HOST
          value: "redis"

