apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-fast
  template:
    metadata:
      labels:
        app: worker-fast
    spec:
      containers:
      - name: worker
        image: worker:latest
        env:
        - name: MODE
          value: "FAST"
        - name: REDIS_HOST
          value: "redis"

